### ISSUE TITLE
can add pause state

### ISSUE THREAD

**Issue by cherishloveyou** [pwillsey/PWProgressView#4]

**Comment by pwillsey** [comment]
Sure I'll look into adding this

**Comment by cherishloveyou** [comment]
Actually,I had made a similar pause icon with UIBezierPath. but there is a problem, i don't how to composition with progress state like app installing animation pause state.  And I found another problem,
when the radius is less than 60 px , the circle is not round. seem it's too shape, I capture a png file.
![ios simulator screen shot aug 30 2015 12 26 51 am copy](https://cloud.githubusercontent.com/assets/1764796/9563160/38014656-4eae-11e5-9aae-0e0bdb2a071b.png)

**Comment by pwillsey** [comment]
Sorry for the delay, but I added a pause state if you're still interested, it's available in the branch 'pause_button'. Let me know what you think.

**Comment by cherishloveyou** [comment]
awesome,much better than i do. Thanks
